export const articleLibrary = [
   {
      id: 1,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-169",
      title: "Nudo Noodle",
      profile: "Workbyworks",
      profileHref: "/profile/workbyworks",
      src: "https://www.datocms-assets.com/79148/1771819936-designeverywhere_library_nudonoodle_2.webp?auto=format%2Ccompress&q=75",
      location: "Chengdu",
      tags: [
         { href: "/industry/food", name: "Food" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 2,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-168",
      title: "Velorah",
      profile: "Agency",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-velorah-preview-CJNTtbpd.gif",
      location: "Kaunas",
      tags: [
         { href: "/industry/food", name: "Food" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 3,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-167",
      title: "Aetheris Voyage",
      profile: "Hero Section",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-aetheris-voyage-preview-BGJn1z4t.gif",
      location: "California",
      tags: [
         { href: "/industry/food", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 4,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-166",
      title: "Urban Jungle",
      profile: "Landing Page",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-urban-jungle-preview-DUD-6bVK.gif",
      location: "Berlin",
      tags: [
         { href: "/industry/food", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 5,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-165",
      title: "Slam Dunk",
      profile: "Hero Section",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-slam-dunk-preview-Cmg3K_S4.gif",
      location: "HongKong",
      tags: [
         { href: "/industry/food", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 6,
      type: "video",
      href: "/work/nudo-noodle",
      wk: "WK-164",
      title: "Omidyar Network",
      profile: "20(SOMETHING)",
      profileHref: "/profile/20-something",
      src: "https://player.vimeo.com/progressive_redirect/playback/1099377722/rendition/1080p/file.mp4?loc=external&log_user=0&signature=f537af8f6842937dd67c91bcc21ff9f0488996ea97d3b9eb500018b8b84411bb",
      location: "San Francisco",
      tags: [
         { href: "/industry/finance", name: "Finance" },
         { href: "/typeofwork/digital-design", name: "Digital Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
      ],
   },
   {
      id: 7,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-163",
      title: "Liquid Glass Agency",
      profile: "Landing Page",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-liquid-glass-agency-preview-Cr5Q9-lc.gif",
      location: "Porto",
      tags: [
         { href: "/industry/food", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 8,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-162",
      title: "3D Portfolio",
      profile: "Portfolio",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-3d-jack-portfolio-preview-BS06Nx21.gif",
      location: "New York",
      tags: [
         { href: "/industry/food", name: "Portfolio" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 9,
      type: "video",
      href: "https://designeverywhere.co/library/1",
      wk: "WK-154",
      title: "Maiella",
      profile: "Multiverse Studio",
      profileHref: "https://designeverywhere.co/work/maiella",
      src: "https://player.vimeo.com/progressive_redirect/playback/1075243393/rendition/1080p/file.mp4?loc=external&log_user=0&signature=3351fbea594d7aa1058c855f8afdb578b80873091cdeaa34f64473d8ac2a27de",
      location: "Salerno",
      tags: [
         { href: "/industry/finance", name: "Technology" },
         { href: "/typeofwork/digital-design", name: "Digital Design" },
         { href: "/typeofwork/logo-design", name: "Typography" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
      ],
   },
   {
      id: 10,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-161",
      title: "Sessions",
      profile: "OMSE",
      profileHref: "https://designeverywhere.co/profile/omse",
      src: "https://www.datocms-assets.com/79148/1744796200-designeverywhere_library_sessions_1.webp?auto=format%2Ccompress&q=75",
      location: "London",
      tags: [
         { href: "/industry/food", name: "Food" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 11,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-160",
      title: "Prisma Creative Studio",
      profile: "Landing Page",
      profileHref: "https://designeverywhere.co/profile/omse",
      src: "https://motionsites.ai/assets/hero-prisma-preview-D4QeI0Bn.gif",
      location: "China",
      tags: [
         { href: "/industry/food", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 12,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-159",
      title: "Nike Premium Landing",
      profile: "Landing Page",
      profileHref: "https://designeverywhere.co/profile/omse",
      src: "https://motionsites.ai/assets/hero-nike-premium-landing-preview-_VyIBlIe.gif",
      location: "Munich",
      tags: [
         { href: "/industry/food", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 13,
      type: "video",
      href: "https://designeverywhere.co/work/mafate-x",
      wk: "WK-158",
      title: "Mafate X",
      profile: "LOS YORK",
      profileHref: "https://designeverywhere.co/work/mafate-x",
      src: "https://player.vimeo.com/progressive_redirect/playback/1090018025/rendition/1080p/file.mp4?loc=external&log_user=0&signature=70fce88ea52c81d0bf7924d41b3456c44d8fdd09c4f279ae10741c2743e4ed1d",
      location: "Los Angeles",
      tags: [
         { href: "/industry/fashion", name: "Fashion" },
         { href: "/typeofwork/sports", name: "Sports" },
         { href: "/typeofwork/campaigns", name: "Campaigns" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
      ],
   },
   {
      id: 14,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-157",
      title: "Impressive Hero",
      profile: "Hero Section",
      profileHref: "https://designeverywhere.co/profile/omse",
      src: "https://motionsites.ai/assets/hero-impressive-preview-BCJtlSs2.gif",
      location: "Brussels",
      tags: [
         { href: "/industry/food", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 15,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-156",
      title: "RRE Ventures",
      profile: "Studio Freight",
      profileHref: "https://designeverywhere.co/profile/omse",
      src: "https://www.datocms-assets.com/79148/1750742102-designeverywhere_library_rreventures_9.webp?auto=format%2Ccompress&q=75",
      location: "New York",
      tags: [
         { href: "/industry/finance", name: "Finance" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 16,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-155",
      title: "Asme",
      profile: "Hero Section",
      profileHref: "https://designeverywhere.co/profile/asme",
      src: "https://motionsites.ai/assets/hero-asme-preview-B_nGDnTP.gif",
      location: "Tokio",
      tags: [
         { href: "/industry/finance", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 17,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-154",
      title: "VEX Ventures",
      profile: "Hero Section",
      profileHref: "https://designeverywhere.co/profile/asme",
      src: "https://motionsites.ai/assets/hero-vex-ventures-preview-BczMFIiw.gif",
      location: "Mexico",
      tags: [
         { href: "/industry/finance", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 18,
      type: "image",
      href: "https://motionsites.ai/assets/hero-guardnet-preview-DAQqiNXC.gif",
      wk: "WK-153",
      title: "Guardnet",
      profile: "Landing Page",
      profileHref: "https://designeverywhere.co/profile/asme",
      src: "https://motionsites.ai/assets/hero-guardnet-preview-DAQqiNXC.gif",
      location: "Ibiza",
      tags: [
         { href: "/industry/finance", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
   {
      id: 19,
      type: "image",
      href: "https://motionsites.ai/assets/hero-wisa-space-preview-CAIFtU8c.gif",
      wk: "WK-152",
      title: "WISA Space",
      profile: "Hero Section",
      profileHref: "https://designeverywhere.co/profile/asme",
      src: "https://motionsites.ai/assets/hero-wisa-space-preview-CAIFtU8c.gif",
      location: "Zurih",
      tags: [
         { href: "/industry/finance", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
   {
      id: 20,
      type: "image",
      href: "https://www.datocms-assets.com/79148/1714991624-designeverywhere_library_cliik_2.webp?auto=format%2Ccompress&q=75",
      wk: "WK-151",
      title: "Cliik",
      profile: "Little Troop",
      profileHref: "https://designeverywhere.co/profile/little-troop",
      src: "https://www.datocms-assets.com/79148/1714991624-designeverywhere_library_cliik_2.webp?auto=format%2Ccompress&q=75",
      location: " Xi'An",
      tags: [
         { href: "/industry/finance", name: "Home" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
   {
      id: 21,
      type: "image",
      href: "https://motionsites.ai/assets/hero-portal-preview-DEscBr2T.gif",
      wk: "WK-150",
      title: "Portal",
      profile: "Hero Section",
      profileHref: "https://designeverywhere.co/profile/little-troop",
      src: "https://motionsites.ai/assets/hero-portal-preview-DEscBr2T.gif",
      location: "Xi'An",
      tags: [
         { href: "/industry/finance", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
   {
      id: 22,
      type: "video",
      href: "https://player.vimeo.com/progressive_redirect/playback/1061259649/rendition/1080p/file.mp4?loc=external&log_user=0&signature=335605aa2b025638a6e96ff4e91483f93e1669cbd9fb3a0c9462228338bb468e&user_id=5652942",
      wk: "WK-149",
      title: "Tezza",
      profile: "Saint-Urbain",
      profileHref: "https://designeverywhere.co/profile/saint-urbain",
      src: "https://player.vimeo.com/progressive_redirect/playback/1061259649/rendition/1080p/file.mp4?loc=external&log_user=0&signature=335605aa2b025638a6e96ff4e91483f93e1669cbd9fb3a0c9462228338bb468e&user_id=5652942",
      location: "Los Angeles",
      tags: [
         { href: "/industry/fashion", name: "Arts & Culture" },
         { href: "/typeofwork/sports", name: "Logo Design" },
         { href: "/typeofwork/campaigns", name: "Campaigns" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
      ],
   },
   {
      id: 23,
      type: "image",
      href: "https://motionsites.ai/assets/hero-orbis-nft-preview-C3wvh77a.gif",
      wk: "WK-148",
      title: "Orbis NFT",
      profile: "Landing Page",
      profileHref: "https://designeverywhere.co/profile/little-troop",
      src: "https://motionsites.ai/assets/hero-orbis-nft-preview-C3wvh77a.gif",
      location: "Paris",
      tags: [
         { href: "/industry/finance", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
    {
      id: 24,
      type: "image",
      href: "https://motionsites.ai/assets/hero-focus-ai-preview-Bnad3D1L.gif",
      wk: "WK-148",
      title: "Focus AI",
      profile: "Landing Page",
      profileHref: "https://designeverywhere.co/profile/little-troop",
      src: "https://motionsites.ai/assets/hero-focus-ai-preview-Bnad3D1L.gif",
      location: "London",
      tags: [
         { href: "/industry/finance", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
      {
      id: 25,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-169",
      title: "Nudo Noodle",
      profile: "Workbyworks",
      profileHref: "/profile/workbyworks",
      src: "https://www.datocms-assets.com/79148/1771819936-designeverywhere_library_nudonoodle_2.webp?auto=format%2Ccompress&q=75",
      location: "Chengdu",
      tags: [
         { href: "/industry/food", name: "Food" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 26,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-168",
      title: "Velorah",
      profile: "Agency",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-velorah-preview-CJNTtbpd.gif",
      location: "Kaunas",
      tags: [
         { href: "/industry/food", name: "Food" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 27,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-167",
      title: "Aetheris Voyage",
      profile: "Hero Section",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-aetheris-voyage-preview-BGJn1z4t.gif",
      location: "California",
      tags: [
         { href: "/industry/food", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 28,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-166",
      title: "Urban Jungle",
      profile: "Landing Page",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-urban-jungle-preview-DUD-6bVK.gif",
      location: "Berlin",
      tags: [
         { href: "/industry/food", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 29,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-165",
      title: "Slam Dunk",
      profile: "Hero Section",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-slam-dunk-preview-Cmg3K_S4.gif",
      location: "HongKong",
      tags: [
         { href: "/industry/food", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 30,
      type: "video",
      href: "/work/nudo-noodle",
      wk: "WK-164",
      title: "Omidyar Network",
      profile: "20(SOMETHING)",
      profileHref: "/profile/20-something",
      src: "https://player.vimeo.com/progressive_redirect/playback/1099377722/rendition/1080p/file.mp4?loc=external&log_user=0&signature=f537af8f6842937dd67c91bcc21ff9f0488996ea97d3b9eb500018b8b84411bb",
      location: "San Francisco",
      tags: [
         { href: "/industry/finance", name: "Finance" },
         { href: "/typeofwork/digital-design", name: "Digital Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
      ],
   },
   {
      id: 31,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-163",
      title: "Liquid Glass Agency",
      profile: "Landing Page",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-liquid-glass-agency-preview-Cr5Q9-lc.gif",
      location: "Porto",
      tags: [
         { href: "/industry/food", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 32,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-162",
      title: "3D Portfolio",
      profile: "Portfolio",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-3d-jack-portfolio-preview-BS06Nx21.gif",
      location: "New York",
      tags: [
         { href: "/industry/food", name: "Portfolio" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 33,
      type: "video",
      href: "https://designeverywhere.co/library/1",
      wk: "WK-154",
      title: "Maiella",
      profile: "Multiverse Studio",
      profileHref: "https://designeverywhere.co/work/maiella",
      src: "https://player.vimeo.com/progressive_redirect/playback/1075243393/rendition/1080p/file.mp4?loc=external&log_user=0&signature=3351fbea594d7aa1058c855f8afdb578b80873091cdeaa34f64473d8ac2a27de",
      location: "Salerno",
      tags: [
         { href: "/industry/finance", name: "Technology" },
         { href: "/typeofwork/digital-design", name: "Digital Design" },
         { href: "/typeofwork/logo-design", name: "Typography" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
      ],
   },
   {
      id: 34,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-161",
      title: "Sessions",
      profile: "OMSE",
      profileHref: "https://designeverywhere.co/profile/omse",
      src: "https://www.datocms-assets.com/79148/1744796200-designeverywhere_library_sessions_1.webp?auto=format%2Ccompress&q=75",
      location: "London",
      tags: [
         { href: "/industry/food", name: "Food" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 35,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-160",
      title: "Prisma Creative Studio",
      profile: "Landing Page",
      profileHref: "https://designeverywhere.co/profile/omse",
      src: "https://motionsites.ai/assets/hero-prisma-preview-D4QeI0Bn.gif",
      location: "China",
      tags: [
         { href: "/industry/food", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 36,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-159",
      title: "Nike Premium Landing",
      profile: "Landing Page",
      profileHref: "https://designeverywhere.co/profile/omse",
      src: "https://motionsites.ai/assets/hero-nike-premium-landing-preview-_VyIBlIe.gif",
      location: "Munich",
      tags: [
         { href: "/industry/food", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 37,
      type: "video",
      href: "https://designeverywhere.co/work/mafate-x",
      wk: "WK-158",
      title: "Mafate X",
      profile: "LOS YORK",
      profileHref: "https://designeverywhere.co/work/mafate-x",
      src: "https://player.vimeo.com/progressive_redirect/playback/1090018025/rendition/1080p/file.mp4?loc=external&log_user=0&signature=70fce88ea52c81d0bf7924d41b3456c44d8fdd09c4f279ae10741c2743e4ed1d",
      location: "Los Angeles",
      tags: [
         { href: "/industry/fashion", name: "Fashion" },
         { href: "/typeofwork/sports", name: "Sports" },
         { href: "/typeofwork/campaigns", name: "Campaigns" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
      ],
   },
   {
      id: 38,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-157",
      title: "Impressive Hero",
      profile: "Hero Section",
      profileHref: "https://designeverywhere.co/profile/omse",
      src: "https://motionsites.ai/assets/hero-impressive-preview-BCJtlSs2.gif",
      location: "Brussels",
      tags: [
         { href: "/industry/food", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 39,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-156",
      title: "RRE Ventures",
      profile: "Studio Freight",
      profileHref: "https://designeverywhere.co/profile/omse",
      src: "https://www.datocms-assets.com/79148/1750742102-designeverywhere_library_rreventures_9.webp?auto=format%2Ccompress&q=75",
      location: "New York",
      tags: [
         { href: "/industry/finance", name: "Finance" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 40,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-155",
      title: "Asme",
      profile: "Hero Section",
      profileHref: "https://designeverywhere.co/profile/asme",
      src: "https://motionsites.ai/assets/hero-asme-preview-B_nGDnTP.gif",
      location: "Tokio",
      tags: [
         { href: "/industry/finance", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 41,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-154",
      title: "VEX Ventures",
      profile: "Hero Section",
      profileHref: "https://designeverywhere.co/profile/asme",
      src: "https://motionsites.ai/assets/hero-vex-ventures-preview-BczMFIiw.gif",
      location: "Mexico",
      tags: [
         { href: "/industry/finance", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 42,
      type: "image",
      href: "https://motionsites.ai/assets/hero-guardnet-preview-DAQqiNXC.gif",
      wk: "WK-153",
      title: "Guardnet",
      profile: "Landing Page",
      profileHref: "https://designeverywhere.co/profile/asme",
      src: "https://motionsites.ai/assets/hero-guardnet-preview-DAQqiNXC.gif",
      location: "Ibiza",
      tags: [
         { href: "/industry/finance", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
   {
      id: 43,
      type: "image",
      href: "https://motionsites.ai/assets/hero-wisa-space-preview-CAIFtU8c.gif",
      wk: "WK-152",
      title: "WISA Space",
      profile: "Hero Section",
      profileHref: "https://designeverywhere.co/profile/asme",
      src: "https://motionsites.ai/assets/hero-wisa-space-preview-CAIFtU8c.gif",
      location: "Zurih",
      tags: [
         { href: "/industry/finance", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
   {
      id: 44,
      type: "image",
      href: "https://www.datocms-assets.com/79148/1714991624-designeverywhere_library_cliik_2.webp?auto=format%2Ccompress&q=75",
      wk: "WK-151",
      title: "Cliik",
      profile: "Little Troop",
      profileHref: "https://designeverywhere.co/profile/little-troop",
      src: "https://www.datocms-assets.com/79148/1714991624-designeverywhere_library_cliik_2.webp?auto=format%2Ccompress&q=75",
      location: " Xi'An",
      tags: [
         { href: "/industry/finance", name: "Home" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
   {
      id: 45,
      type: "image",
      href: "https://motionsites.ai/assets/hero-portal-preview-DEscBr2T.gif",
      wk: "WK-150",
      title: "Portal",
      profile: "Hero Section",
      profileHref: "https://designeverywhere.co/profile/little-troop",
      src: "https://motionsites.ai/assets/hero-portal-preview-DEscBr2T.gif",
      location: "Xi'An",
      tags: [
         { href: "/industry/finance", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
   {
      id: 46,
      type: "video",
      href: "https://player.vimeo.com/progressive_redirect/playback/1061259649/rendition/1080p/file.mp4?loc=external&log_user=0&signature=335605aa2b025638a6e96ff4e91483f93e1669cbd9fb3a0c9462228338bb468e&user_id=5652942",
      wk: "WK-149",
      title: "Tezza",
      profile: "Saint-Urbain",
      profileHref: "https://designeverywhere.co/profile/saint-urbain",
      src: "https://player.vimeo.com/progressive_redirect/playback/1061259649/rendition/1080p/file.mp4?loc=external&log_user=0&signature=335605aa2b025638a6e96ff4e91483f93e1669cbd9fb3a0c9462228338bb468e&user_id=5652942",
      location: "Los Angeles",
      tags: [
         { href: "/industry/fashion", name: "Arts & Culture" },
         { href: "/typeofwork/sports", name: "Logo Design" },
         { href: "/typeofwork/campaigns", name: "Campaigns" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
      ],
   },
   {
      id: 47,
      type: "image",
      href: "https://motionsites.ai/assets/hero-orbis-nft-preview-C3wvh77a.gif",
      wk: "WK-148",
      title: "Orbis NFT",
      profile: "Landing Page",
      profileHref: "https://designeverywhere.co/profile/little-troop",
      src: "https://motionsites.ai/assets/hero-orbis-nft-preview-C3wvh77a.gif",
      location: "Paris",
      tags: [
         { href: "/industry/finance", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
    {
      id: 48,
      type: "image",
      href: "https://motionsites.ai/assets/hero-focus-ai-preview-Bnad3D1L.gif",
      wk: "WK-148",
      title: "Focus AI",
      profile: "Landing Page",
      profileHref: "https://designeverywhere.co/profile/little-troop",
      src: "https://motionsites.ai/assets/hero-focus-ai-preview-Bnad3D1L.gif",
      location: "London",
      tags: [
         { href: "/industry/finance", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
      {
      id: 1,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-169",
      title: "Nudo Noodle",
      profile: "Workbyworks",
      profileHref: "/profile/workbyworks",
      src: "https://www.datocms-assets.com/79148/1771819936-designeverywhere_library_nudonoodle_2.webp?auto=format%2Ccompress&q=75",
      location: "Chengdu",
      tags: [
         { href: "/industry/food", name: "Food" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 2,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-168",
      title: "Velorah",
      profile: "Agency",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-velorah-preview-CJNTtbpd.gif",
      location: "Kaunas",
      tags: [
         { href: "/industry/food", name: "Food" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 3,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-167",
      title: "Aetheris Voyage",
      profile: "Hero Section",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-aetheris-voyage-preview-BGJn1z4t.gif",
      location: "California",
      tags: [
         { href: "/industry/food", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 4,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-166",
      title: "Urban Jungle",
      profile: "Landing Page",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-urban-jungle-preview-DUD-6bVK.gif",
      location: "Berlin",
      tags: [
         { href: "/industry/food", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 5,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-165",
      title: "Slam Dunk",
      profile: "Hero Section",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-slam-dunk-preview-Cmg3K_S4.gif",
      location: "HongKong",
      tags: [
         { href: "/industry/food", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 6,
      type: "video",
      href: "/work/nudo-noodle",
      wk: "WK-164",
      title: "Omidyar Network",
      profile: "20(SOMETHING)",
      profileHref: "/profile/20-something",
      src: "https://player.vimeo.com/progressive_redirect/playback/1099377722/rendition/1080p/file.mp4?loc=external&log_user=0&signature=f537af8f6842937dd67c91bcc21ff9f0488996ea97d3b9eb500018b8b84411bb",
      location: "San Francisco",
      tags: [
         { href: "/industry/finance", name: "Finance" },
         { href: "/typeofwork/digital-design", name: "Digital Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
      ],
   },
   {
      id: 7,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-163",
      title: "Liquid Glass Agency",
      profile: "Landing Page",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-liquid-glass-agency-preview-Cr5Q9-lc.gif",
      location: "Porto",
      tags: [
         { href: "/industry/food", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 8,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-162",
      title: "3D Portfolio",
      profile: "Portfolio",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-3d-jack-portfolio-preview-BS06Nx21.gif",
      location: "New York",
      tags: [
         { href: "/industry/food", name: "Portfolio" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 9,
      type: "video",
      href: "https://designeverywhere.co/library/1",
      wk: "WK-154",
      title: "Maiella",
      profile: "Multiverse Studio",
      profileHref: "https://designeverywhere.co/work/maiella",
      src: "https://player.vimeo.com/progressive_redirect/playback/1075243393/rendition/1080p/file.mp4?loc=external&log_user=0&signature=3351fbea594d7aa1058c855f8afdb578b80873091cdeaa34f64473d8ac2a27de",
      location: "Salerno",
      tags: [
         { href: "/industry/finance", name: "Technology" },
         { href: "/typeofwork/digital-design", name: "Digital Design" },
         { href: "/typeofwork/logo-design", name: "Typography" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
      ],
   },
   {
      id: 10,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-161",
      title: "Sessions",
      profile: "OMSE",
      profileHref: "https://designeverywhere.co/profile/omse",
      src: "https://www.datocms-assets.com/79148/1744796200-designeverywhere_library_sessions_1.webp?auto=format%2Ccompress&q=75",
      location: "London",
      tags: [
         { href: "/industry/food", name: "Food" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 11,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-160",
      title: "Prisma Creative Studio",
      profile: "Landing Page",
      profileHref: "https://designeverywhere.co/profile/omse",
      src: "https://motionsites.ai/assets/hero-prisma-preview-D4QeI0Bn.gif",
      location: "China",
      tags: [
         { href: "/industry/food", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 12,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-159",
      title: "Nike Premium Landing",
      profile: "Landing Page",
      profileHref: "https://designeverywhere.co/profile/omse",
      src: "https://motionsites.ai/assets/hero-nike-premium-landing-preview-_VyIBlIe.gif",
      location: "Munich",
      tags: [
         { href: "/industry/food", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 13,
      type: "video",
      href: "https://designeverywhere.co/work/mafate-x",
      wk: "WK-158",
      title: "Mafate X",
      profile: "LOS YORK",
      profileHref: "https://designeverywhere.co/work/mafate-x",
      src: "https://player.vimeo.com/progressive_redirect/playback/1090018025/rendition/1080p/file.mp4?loc=external&log_user=0&signature=70fce88ea52c81d0bf7924d41b3456c44d8fdd09c4f279ae10741c2743e4ed1d",
      location: "Los Angeles",
      tags: [
         { href: "/industry/fashion", name: "Fashion" },
         { href: "/typeofwork/sports", name: "Sports" },
         { href: "/typeofwork/campaigns", name: "Campaigns" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
      ],
   },
   {
      id: 14,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-157",
      title: "Impressive Hero",
      profile: "Hero Section",
      profileHref: "https://designeverywhere.co/profile/omse",
      src: "https://motionsites.ai/assets/hero-impressive-preview-BCJtlSs2.gif",
      location: "Brussels",
      tags: [
         { href: "/industry/food", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 15,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-156",
      title: "RRE Ventures",
      profile: "Studio Freight",
      profileHref: "https://designeverywhere.co/profile/omse",
      src: "https://www.datocms-assets.com/79148/1750742102-designeverywhere_library_rreventures_9.webp?auto=format%2Ccompress&q=75",
      location: "New York",
      tags: [
         { href: "/industry/finance", name: "Finance" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 16,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-155",
      title: "Asme",
      profile: "Hero Section",
      profileHref: "https://designeverywhere.co/profile/asme",
      src: "https://motionsites.ai/assets/hero-asme-preview-B_nGDnTP.gif",
      location: "Tokio",
      tags: [
         { href: "/industry/finance", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 17,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-154",
      title: "VEX Ventures",
      profile: "Hero Section",
      profileHref: "https://designeverywhere.co/profile/asme",
      src: "https://motionsites.ai/assets/hero-vex-ventures-preview-BczMFIiw.gif",
      location: "Mexico",
      tags: [
         { href: "/industry/finance", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 18,
      type: "image",
      href: "https://motionsites.ai/assets/hero-guardnet-preview-DAQqiNXC.gif",
      wk: "WK-153",
      title: "Guardnet",
      profile: "Landing Page",
      profileHref: "https://designeverywhere.co/profile/asme",
      src: "https://motionsites.ai/assets/hero-guardnet-preview-DAQqiNXC.gif",
      location: "Ibiza",
      tags: [
         { href: "/industry/finance", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
   {
      id: 19,
      type: "image",
      href: "https://motionsites.ai/assets/hero-wisa-space-preview-CAIFtU8c.gif",
      wk: "WK-152",
      title: "WISA Space",
      profile: "Hero Section",
      profileHref: "https://designeverywhere.co/profile/asme",
      src: "https://motionsites.ai/assets/hero-wisa-space-preview-CAIFtU8c.gif",
      location: "Zurih",
      tags: [
         { href: "/industry/finance", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
   {
      id: 20,
      type: "image",
      href: "https://www.datocms-assets.com/79148/1714991624-designeverywhere_library_cliik_2.webp?auto=format%2Ccompress&q=75",
      wk: "WK-151",
      title: "Cliik",
      profile: "Little Troop",
      profileHref: "https://designeverywhere.co/profile/little-troop",
      src: "https://www.datocms-assets.com/79148/1714991624-designeverywhere_library_cliik_2.webp?auto=format%2Ccompress&q=75",
      location: " Xi'An",
      tags: [
         { href: "/industry/finance", name: "Home" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
   {
      id: 21,
      type: "image",
      href: "https://motionsites.ai/assets/hero-portal-preview-DEscBr2T.gif",
      wk: "WK-150",
      title: "Portal",
      profile: "Hero Section",
      profileHref: "https://designeverywhere.co/profile/little-troop",
      src: "https://motionsites.ai/assets/hero-portal-preview-DEscBr2T.gif",
      location: "Xi'An",
      tags: [
         { href: "/industry/finance", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
   {
      id: 22,
      type: "video",
      href: "https://player.vimeo.com/progressive_redirect/playback/1061259649/rendition/1080p/file.mp4?loc=external&log_user=0&signature=335605aa2b025638a6e96ff4e91483f93e1669cbd9fb3a0c9462228338bb468e&user_id=5652942",
      wk: "WK-149",
      title: "Tezza",
      profile: "Saint-Urbain",
      profileHref: "https://designeverywhere.co/profile/saint-urbain",
      src: "https://player.vimeo.com/progressive_redirect/playback/1061259649/rendition/1080p/file.mp4?loc=external&log_user=0&signature=335605aa2b025638a6e96ff4e91483f93e1669cbd9fb3a0c9462228338bb468e&user_id=5652942",
      location: "Los Angeles",
      tags: [
         { href: "/industry/fashion", name: "Arts & Culture" },
         { href: "/typeofwork/sports", name: "Logo Design" },
         { href: "/typeofwork/campaigns", name: "Campaigns" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
      ],
   },
   {
      id: 23,
      type: "image",
      href: "https://motionsites.ai/assets/hero-orbis-nft-preview-C3wvh77a.gif",
      wk: "WK-148",
      title: "Orbis NFT",
      profile: "Landing Page",
      profileHref: "https://designeverywhere.co/profile/little-troop",
      src: "https://motionsites.ai/assets/hero-orbis-nft-preview-C3wvh77a.gif",
      location: "Paris",
      tags: [
         { href: "/industry/finance", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
    {
      id: 24,
      type: "image",
      href: "https://motionsites.ai/assets/hero-focus-ai-preview-Bnad3D1L.gif",
      wk: "WK-148",
      title: "Focus AI",
      profile: "Landing Page",
      profileHref: "https://designeverywhere.co/profile/little-troop",
      src: "https://motionsites.ai/assets/hero-focus-ai-preview-Bnad3D1L.gif",
      location: "London",
      tags: [
         { href: "/industry/finance", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
      {
      id: 25,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-169",
      title: "Nudo Noodle",
      profile: "Workbyworks",
      profileHref: "/profile/workbyworks",
      src: "https://www.datocms-assets.com/79148/1771819936-designeverywhere_library_nudonoodle_2.webp?auto=format%2Ccompress&q=75",
      location: "Chengdu",
      tags: [
         { href: "/industry/food", name: "Food" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 26,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-168",
      title: "Velorah",
      profile: "Agency",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-velorah-preview-CJNTtbpd.gif",
      location: "Kaunas",
      tags: [
         { href: "/industry/food", name: "Food" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 27,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-167",
      title: "Aetheris Voyage",
      profile: "Hero Section",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-aetheris-voyage-preview-BGJn1z4t.gif",
      location: "California",
      tags: [
         { href: "/industry/food", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 28,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-166",
      title: "Urban Jungle",
      profile: "Landing Page",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-urban-jungle-preview-DUD-6bVK.gif",
      location: "Berlin",
      tags: [
         { href: "/industry/food", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 29,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-165",
      title: "Slam Dunk",
      profile: "Hero Section",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-slam-dunk-preview-Cmg3K_S4.gif",
      location: "HongKong",
      tags: [
         { href: "/industry/food", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 30,
      type: "video",
      href: "/work/nudo-noodle",
      wk: "WK-164",
      title: "Omidyar Network",
      profile: "20(SOMETHING)",
      profileHref: "/profile/20-something",
      src: "https://player.vimeo.com/progressive_redirect/playback/1099377722/rendition/1080p/file.mp4?loc=external&log_user=0&signature=f537af8f6842937dd67c91bcc21ff9f0488996ea97d3b9eb500018b8b84411bb",
      location: "San Francisco",
      tags: [
         { href: "/industry/finance", name: "Finance" },
         { href: "/typeofwork/digital-design", name: "Digital Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
      ],
   },
   {
      id: 31,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-163",
      title: "Liquid Glass Agency",
      profile: "Landing Page",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-liquid-glass-agency-preview-Cr5Q9-lc.gif",
      location: "Porto",
      tags: [
         { href: "/industry/food", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 32,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-162",
      title: "3D Portfolio",
      profile: "Portfolio",
      profileHref: "/profile/workbyworks",
      src: "https://motionsites.ai/assets/hero-3d-jack-portfolio-preview-BS06Nx21.gif",
      location: "New York",
      tags: [
         { href: "/industry/food", name: "Portfolio" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 33,
      type: "video",
      href: "https://designeverywhere.co/library/1",
      wk: "WK-154",
      title: "Maiella",
      profile: "Multiverse Studio",
      profileHref: "https://designeverywhere.co/work/maiella",
      src: "https://player.vimeo.com/progressive_redirect/playback/1075243393/rendition/1080p/file.mp4?loc=external&log_user=0&signature=3351fbea594d7aa1058c855f8afdb578b80873091cdeaa34f64473d8ac2a27de",
      location: "Salerno",
      tags: [
         { href: "/industry/finance", name: "Technology" },
         { href: "/typeofwork/digital-design", name: "Digital Design" },
         { href: "/typeofwork/logo-design", name: "Typography" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
      ],
   },
   {
      id: 34,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-161",
      title: "Sessions",
      profile: "OMSE",
      profileHref: "https://designeverywhere.co/profile/omse",
      src: "https://www.datocms-assets.com/79148/1744796200-designeverywhere_library_sessions_1.webp?auto=format%2Ccompress&q=75",
      location: "London",
      tags: [
         { href: "/industry/food", name: "Food" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 35,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-160",
      title: "Prisma Creative Studio",
      profile: "Landing Page",
      profileHref: "https://designeverywhere.co/profile/omse",
      src: "https://motionsites.ai/assets/hero-prisma-preview-D4QeI0Bn.gif",
      location: "China",
      tags: [
         { href: "/industry/food", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 36,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-159",
      title: "Nike Premium Landing",
      profile: "Landing Page",
      profileHref: "https://designeverywhere.co/profile/omse",
      src: "https://motionsites.ai/assets/hero-nike-premium-landing-preview-_VyIBlIe.gif",
      location: "Munich",
      tags: [
         { href: "/industry/food", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 37,
      type: "video",
      href: "https://designeverywhere.co/work/mafate-x",
      wk: "WK-158",
      title: "Mafate X",
      profile: "LOS YORK",
      profileHref: "https://designeverywhere.co/work/mafate-x",
      src: "https://player.vimeo.com/progressive_redirect/playback/1090018025/rendition/1080p/file.mp4?loc=external&log_user=0&signature=70fce88ea52c81d0bf7924d41b3456c44d8fdd09c4f279ae10741c2743e4ed1d",
      location: "Los Angeles",
      tags: [
         { href: "/industry/fashion", name: "Fashion" },
         { href: "/typeofwork/sports", name: "Sports" },
         { href: "/typeofwork/campaigns", name: "Campaigns" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
      ],
   },
   {
      id: 38,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-157",
      title: "Impressive Hero",
      profile: "Hero Section",
      profileHref: "https://designeverywhere.co/profile/omse",
      src: "https://motionsites.ai/assets/hero-impressive-preview-BCJtlSs2.gif",
      location: "Brussels",
      tags: [
         { href: "/industry/food", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 39,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-156",
      title: "RRE Ventures",
      profile: "Studio Freight",
      profileHref: "https://designeverywhere.co/profile/omse",
      src: "https://www.datocms-assets.com/79148/1750742102-designeverywhere_library_rreventures_9.webp?auto=format%2Ccompress&q=75",
      location: "New York",
      tags: [
         { href: "/industry/finance", name: "Finance" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 40,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-155",
      title: "Asme",
      profile: "Hero Section",
      profileHref: "https://designeverywhere.co/profile/asme",
      src: "https://motionsites.ai/assets/hero-asme-preview-B_nGDnTP.gif",
      location: "Tokio",
      tags: [
         { href: "/industry/finance", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 41,
      type: "image",
      href: "/work/nudo-noodle",
      wk: "WK-154",
      title: "VEX Ventures",
      profile: "Hero Section",
      profileHref: "https://designeverywhere.co/profile/asme",
      src: "https://motionsites.ai/assets/hero-vex-ventures-preview-BczMFIiw.gif",
      location: "Mexico",
      tags: [
         { href: "/industry/finance", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Logo Design" },
         { href: "/typeofwork/packaging", name: "Packaging Design" },
      ],
   },
   {
      id: 42,
      type: "image",
      href: "https://motionsites.ai/assets/hero-guardnet-preview-DAQqiNXC.gif",
      wk: "WK-153",
      title: "Guardnet",
      profile: "Landing Page",
      profileHref: "https://designeverywhere.co/profile/asme",
      src: "https://motionsites.ai/assets/hero-guardnet-preview-DAQqiNXC.gif",
      location: "Ibiza",
      tags: [
         { href: "/industry/finance", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
   {
      id: 43,
      type: "image",
      href: "https://motionsites.ai/assets/hero-wisa-space-preview-CAIFtU8c.gif",
      wk: "WK-152",
      title: "WISA Space",
      profile: "Hero Section",
      profileHref: "https://designeverywhere.co/profile/asme",
      src: "https://motionsites.ai/assets/hero-wisa-space-preview-CAIFtU8c.gif",
      location: "Zurih",
      tags: [
         { href: "/industry/finance", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
   {
      id: 44,
      type: "image",
      href: "https://www.datocms-assets.com/79148/1714991624-designeverywhere_library_cliik_2.webp?auto=format%2Ccompress&q=75",
      wk: "WK-151",
      title: "Cliik",
      profile: "Little Troop",
      profileHref: "https://designeverywhere.co/profile/little-troop",
      src: "https://www.datocms-assets.com/79148/1714991624-designeverywhere_library_cliik_2.webp?auto=format%2Ccompress&q=75",
      location: " Xi'An",
      tags: [
         { href: "/industry/finance", name: "Home" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
   {
      id: 45,
      type: "image",
      href: "https://motionsites.ai/assets/hero-portal-preview-DEscBr2T.gif",
      wk: "WK-150",
      title: "Portal",
      profile: "Hero Section",
      profileHref: "https://designeverywhere.co/profile/little-troop",
      src: "https://motionsites.ai/assets/hero-portal-preview-DEscBr2T.gif",
      location: "Xi'An",
      tags: [
         { href: "/industry/finance", name: "Hero Section" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
   {
      id: 46,
      type: "video",
      href: "https://player.vimeo.com/progressive_redirect/playback/1061259649/rendition/1080p/file.mp4?loc=external&log_user=0&signature=335605aa2b025638a6e96ff4e91483f93e1669cbd9fb3a0c9462228338bb468e&user_id=5652942",
      wk: "WK-149",
      title: "Tezza",
      profile: "Saint-Urbain",
      profileHref: "https://designeverywhere.co/profile/saint-urbain",
      src: "https://player.vimeo.com/progressive_redirect/playback/1061259649/rendition/1080p/file.mp4?loc=external&log_user=0&signature=335605aa2b025638a6e96ff4e91483f93e1669cbd9fb3a0c9462228338bb468e&user_id=5652942",
      location: "Los Angeles",
      tags: [
         { href: "/industry/fashion", name: "Arts & Culture" },
         { href: "/typeofwork/sports", name: "Logo Design" },
         { href: "/typeofwork/campaigns", name: "Campaigns" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
      ],
   },
   {
      id: 47,
      type: "image",
      href: "https://motionsites.ai/assets/hero-orbis-nft-preview-C3wvh77a.gif",
      wk: "WK-148",
      title: "Orbis NFT",
      profile: "Landing Page",
      profileHref: "https://designeverywhere.co/profile/little-troop",
      src: "https://motionsites.ai/assets/hero-orbis-nft-preview-C3wvh77a.gif",
      location: "Paris",
      tags: [
         { href: "/industry/finance", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
    {
      id: 48,
      type: "image",
      href: "https://motionsites.ai/assets/hero-focus-ai-preview-Bnad3D1L.gif",
      wk: "WK-148",
      title: "Focus AI",
      profile: "Landing Page",
      profileHref: "https://designeverywhere.co/profile/little-troop",
      src: "https://motionsites.ai/assets/hero-focus-ai-preview-Bnad3D1L.gif",
      location: "London",
      tags: [
         { href: "/industry/finance", name: "Landing Page" },
         { href: "/typeofwork/brand-identity", name: "Identity Design" },
         { href: "/typeofwork/logo-design", name: "Technology" },
         { href: "/typeofwork/packaging", name: "Website Design" },
      ],
   },
];
